[package]
name = "web-server"
version = "0.1.0"
authors = ["Tim Deeb-Swihart <tim@deebswih.art>"]
edition = "2018"

[dependencies]
error-chain = "0.12.2"
clap = { version = "3.0.0-beta.1"}
dotenv = "0.15.0"
