stages:
  - build

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"

.rust-latest:
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

project1-latest:
  stage: build
  cache:
    paths:
      - project1-kvs/target/
      - .cargo/
  extends: .rust-latest
  before_script:
    - cd project1-kvs
