[package]
name = "kvs"
description = "a key-value store"
version = "0.1.0"
authors = ["Tim Deeb-Swihart <tim@deebswih.art>"]
edition = "2018"

[dependencies]
structopt = "0.3"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"

[lib]

[[bin]]
name = "kvs"
test = false
